spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      # Use ErrorHandlingDeserializer to safely manage SerializationExceptions
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Define the actual delegates
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.LongDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        # Using the safe port 8085 to avoid Windows 8081 conflicts
        schema.registry.url: "http://localhost:8085"
        specific.avro.reader: true