/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.post_service.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PostCreatedEvents extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9161501279572512361L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PostCreatedEvents\",\"namespace\":\"com.example.post_service.events\",\"fields\":[{\"name\":\"creatorId\",\"type\":\"long\",\"default\":0},{\"name\":\"content\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"postId\",\"type\":\"long\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PostCreatedEvents> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PostCreatedEvents> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PostCreatedEvents> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PostCreatedEvents> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PostCreatedEvents> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PostCreatedEvents to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PostCreatedEvents from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PostCreatedEvents instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PostCreatedEvents fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long creatorId;
  private java.lang.String content;
  private long postId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PostCreatedEvents() {}

  /**
   * All-args constructor.
   * @param creatorId The new value for creatorId
   * @param content The new value for content
   * @param postId The new value for postId
   */
  public PostCreatedEvents(java.lang.Long creatorId, java.lang.String content, java.lang.Long postId) {
    this.creatorId = creatorId;
    this.content = content;
    this.postId = postId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return creatorId;
    case 1: return content;
    case 2: return postId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: creatorId = (java.lang.Long)value$; break;
    case 1: content = value$ != null ? value$.toString() : null; break;
    case 2: postId = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'creatorId' field.
   * @return The value of the 'creatorId' field.
   */
  public long getCreatorId() {
    return creatorId;
  }


  /**
   * Sets the value of the 'creatorId' field.
   * @param value the value to set.
   */
  public void setCreatorId(long value) {
    this.creatorId = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.String getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.String value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'postId' field.
   * @return The value of the 'postId' field.
   */
  public long getPostId() {
    return postId;
  }


  /**
   * Sets the value of the 'postId' field.
   * @param value the value to set.
   */
  public void setPostId(long value) {
    this.postId = value;
  }

  /**
   * Creates a new PostCreatedEvents RecordBuilder.
   * @return A new PostCreatedEvents RecordBuilder
   */
  public static com.example.post_service.events.PostCreatedEvents.Builder newBuilder() {
    return new com.example.post_service.events.PostCreatedEvents.Builder();
  }

  /**
   * Creates a new PostCreatedEvents RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PostCreatedEvents RecordBuilder
   */
  public static com.example.post_service.events.PostCreatedEvents.Builder newBuilder(com.example.post_service.events.PostCreatedEvents.Builder other) {
    if (other == null) {
      return new com.example.post_service.events.PostCreatedEvents.Builder();
    } else {
      return new com.example.post_service.events.PostCreatedEvents.Builder(other);
    }
  }

  /**
   * Creates a new PostCreatedEvents RecordBuilder by copying an existing PostCreatedEvents instance.
   * @param other The existing instance to copy.
   * @return A new PostCreatedEvents RecordBuilder
   */
  public static com.example.post_service.events.PostCreatedEvents.Builder newBuilder(com.example.post_service.events.PostCreatedEvents other) {
    if (other == null) {
      return new com.example.post_service.events.PostCreatedEvents.Builder();
    } else {
      return new com.example.post_service.events.PostCreatedEvents.Builder(other);
    }
  }

  /**
   * RecordBuilder for PostCreatedEvents instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PostCreatedEvents>
    implements org.apache.avro.data.RecordBuilder<PostCreatedEvents> {

    private long creatorId;
    private java.lang.String content;
    private long postId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.post_service.events.PostCreatedEvents.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.creatorId)) {
        this.creatorId = data().deepCopy(fields()[0].schema(), other.creatorId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.postId)) {
        this.postId = data().deepCopy(fields()[2].schema(), other.postId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing PostCreatedEvents instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.post_service.events.PostCreatedEvents other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.creatorId)) {
        this.creatorId = data().deepCopy(fields()[0].schema(), other.creatorId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.postId)) {
        this.postId = data().deepCopy(fields()[2].schema(), other.postId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'creatorId' field.
      * @return The value.
      */
    public long getCreatorId() {
      return creatorId;
    }


    /**
      * Sets the value of the 'creatorId' field.
      * @param value The value of 'creatorId'.
      * @return This builder.
      */
    public com.example.post_service.events.PostCreatedEvents.Builder setCreatorId(long value) {
      validate(fields()[0], value);
      this.creatorId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'creatorId' field has been set.
      * @return True if the 'creatorId' field has been set, false otherwise.
      */
    public boolean hasCreatorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'creatorId' field.
      * @return This builder.
      */
    public com.example.post_service.events.PostCreatedEvents.Builder clearCreatorId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.String getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.example.post_service.events.PostCreatedEvents.Builder setContent(java.lang.String value) {
      validate(fields()[1], value);
      this.content = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public com.example.post_service.events.PostCreatedEvents.Builder clearContent() {
      content = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'postId' field.
      * @return The value.
      */
    public long getPostId() {
      return postId;
    }


    /**
      * Sets the value of the 'postId' field.
      * @param value The value of 'postId'.
      * @return This builder.
      */
    public com.example.post_service.events.PostCreatedEvents.Builder setPostId(long value) {
      validate(fields()[2], value);
      this.postId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'postId' field has been set.
      * @return True if the 'postId' field has been set, false otherwise.
      */
    public boolean hasPostId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'postId' field.
      * @return This builder.
      */
    public com.example.post_service.events.PostCreatedEvents.Builder clearPostId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PostCreatedEvents build() {
      try {
        PostCreatedEvents record = new PostCreatedEvents();
        record.creatorId = fieldSetFlags()[0] ? this.creatorId : (java.lang.Long) defaultValue(fields()[0]);
        record.content = fieldSetFlags()[1] ? this.content : (java.lang.String) defaultValue(fields()[1]);
        record.postId = fieldSetFlags()[2] ? this.postId : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PostCreatedEvents>
    WRITER$ = (org.apache.avro.io.DatumWriter<PostCreatedEvents>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PostCreatedEvents>
    READER$ = (org.apache.avro.io.DatumReader<PostCreatedEvents>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.creatorId);

    out.writeString(this.content);

    out.writeLong(this.postId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.creatorId = in.readLong();

      this.content = in.readString();

      this.postId = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.creatorId = in.readLong();
          break;

        case 1:
          this.content = in.readString();
          break;

        case 2:
          this.postId = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










